/* Use this script if you need to support IE 7 and IE 6. */

window.onload = function() {
	function addIcon(el, entity) {
		var html = el.innerHTML;
		el.innerHTML = '<span style="font-family: \'Picons-Font\'">' + entity + '</span>' + html;
	}
	var icons = {
			'picons-attachment' : '&#x61;',
			'picons-bookmarks' : '&#x62;',
			'picons-calendar' : '&#x63;',
			'picons-delete' : '&#x64;',
			'picons-settings' : '&#x65;',
			'picons-facebook' : '&#x66;',
			'picons-graph' : '&#x67;',
			'picons-home' : '&#x68;',
			'picons-image' : '&#x69;',
			'picons-camera' : '&#x6a;',
			'picons-key' : '&#x6b;',
			'picons-lock' : '&#x6c;',
			'picons-mail' : '&#x6d;',
			'picons-compose' : '&#x6e;',
			'picons-open' : '&#x6f;',
			'picons-print' : '&#x70;',
			'picons-close' : '&#x71;',
			'picons-book' : '&#x72;',
			'picons-search' : '&#x73;',
			'picons-twitter' : '&#x74;',
			'picons-upload' : '&#x75;',
			'picons-car' : '&#x76;',
			'picons-world' : '&#x77;',
			'picons-logout' : '&#x78;',
			'picons-user' : '&#x79;',
			'picons-users' : '&#x7a;',
			'picons-call' : '&#x41;',
			'picons-back' : '&#x42;',
			'picons-chat' : '&#x43;',
			'picons-download' : '&#x44;',
			'picons-error' : '&#x45;',
			'picons-find' : '&#x46;',
			'picons-pie' : '&#x47;',
			'picons-house' : '&#x48;',
			'picons-gallery' : '&#x49;',
			'picons-mobile' : '&#x4a;',
			'picons-keyboard' : '&#x4b;',
			'picons-location' : '&#x4c;',
			'picons-map' : '&#x4d;',
			'picons-document' : '&#x4e;',
			'picons-power' : '&#x4f;',
			'picons-pin' : '&#x50;',
			'picons-star' : '&#x51;',
			'picons-star_off' : '&#x52;',
			'picons-settings_2' : '&#x53;',
			'picons-time' : '&#x54;',
			'picons-url' : '&#x55;',
			'picons-video' : '&#x56;',
			'picons-write' : '&#x57;',
			'picons-close-exit' : '&#x58;',
			'picons-yes-success' : '&#x59;',
			'picons-bookmark' : '&#x5a;',
			'picons-switch_off' : '&#x30;',
			'picons-switch_on' : '&#x31;',
			'picons-comment' : '&#x32;',
			'picons-dashboard' : '&#x33;',
			'picons-sound' : '&#x34;',
			'picons-mic' : '&#x35;',
			'picons-music' : '&#x36;',
			'picons-refresh-rotate-sync' : '&#x37;',
			'picons-pdf' : '&#x38;',
			'picons-phonebook' : '&#x39;',
			'picons-minus' : '&#x2d;',
			'picons-plus' : '&#x2b;',
			'picons-cash_register' : '&#x3d;',
			'picons-unable' : '&#x2f;',
			'picons-smiley_happy' : '&#x5b;',
			'picons-smiley_sad' : '&#x5d;',
			'picons-smiley_neutral' : '&#x5c;',
			'picons-no' : '&#x3b;',
			'picons-yes' : '&#x3a;',
			'picons-sign' : '&#x60;',
			'picons-like' : '&#x2e;',
			'picons-dislike' : '&#x2c;',
			'picons-achievement_on' : '&#x22;',
			'picons-achievement_off' : '&#x27;',
			'picons-up' : '&#x7b;',
			'picons-down' : '&#x7d;',
			'picons-play' : '&#x7e;',
			'picons-attention' : '&#x21;',
			'picons-mail_2' : '&#x40;',
			'picons-user_add' : '&#x23;',
			'picons-cash' : '&#x24;',
			'picons-discount' : '&#x25;',
			'picons-cd' : '&#x26;',
			'picons-new' : '&#x2a;',
			'picons-new_2' : '&#x28;',
			'picons-gift' : '&#x29;',
			'picons-left' : '&#x3c;',
			'picons-right' : '&#x3e;',
			'picons-pop_out' : '&#x5e;',
			'picons-help' : '&#x3f;',
			'picons-application' : '&#x5f;',
			'picons-cart' : '&#xa3;',
			'picons-tag' : '&#x20ac;',
			'picons-store' : '&#xa2;',
			'picons-delivery' : '&#xa5;',
			'picons-information' : '&#x7c;',
			'picons-justice' : '&#xa7;',
			'picons-view_list' : '&#xf7;',
			'picons-view_grid' : '&#xf8;',
			'picons-support' : '&#xe6;',
			'picons-flag' : '&#xe7;',
			'picons-visibility' : '&#xd7;',
			'picons-mobile_message' : '&#xe0;',
			'picons-telephone' : '&#xe1;',
			'picons-flip' : '&#xe2;',
			'picons-arrows' : '&#xe3;',
			'picons-website' : '&#xe4;',
			'picons-maximize' : '&#xe5;',
			'picons-minimize' : '&#xe8;',
			'picons-desktop' : '&#xe9;',
			'picons-checklist' : '&#xea;',
			'picons-document_list' : '&#xeb;',
			'picons-activity' : '&#xec;',
			'picons-delete_back' : '&#xed;',
			'picons-control_panel' : '&#xee;',
			'picons-flight' : '&#xef;',
			'picons-credit_card' : '&#xf0;',
			'picons-favorite_remove' : '&#xf1;',
			'picons-favorite_add' : '&#xf2;',
			'picons-favorite_on' : '&#xf3;',
			'picons-favorite_off' : '&#xf4;',
			'picons-thunderbolt' : '&#xf5;',
			'picons-paper_plane' : '&#xf6;',
			'picons-tv' : '&#xf9;',
			'picons-music_on' : '&#xfa;',
			'picons-music_off' : '&#xfb;',
			'picons-google_plus' : '&#xfc;',
			'picons-instagram' : '&#xfd;'
		},
		els = document.getElementsByTagName('*'),
		i, attr, html, c, el;
	for (i = 0; i < els.length; i += 1) {
		el = els[i];
		attr = el.getAttribute('data-icon');
		if (attr) {
			addIcon(el, attr);
		}
		c = el.className;
		c = c.match(/picons-[^\s'"]+/);
		if (c && icons[c[0]]) {
			addIcon(el, icons[c[0]]);
		}
	}
};